/**
 * DE_USTG Ruleset - Deutschland (Umsatzsteuergesetz)
 *
 * Pflichtangaben nach § 14 Abs. 4 UStG
 */

import type { Ruleset } from './types';

export const DE_USTG: Ruleset = {
  ruleset_id: 'DE_USTG',
  version: '1.0.0',
  jurisdiction: 'DE',
  flag: '🇩🇪',
  title_de: 'Deutschland – Umsatzsteuergesetz',
  title_en: 'Germany – VAT Act (UStG)',
  subtitle_de: 'Pflichtangaben nach § 14 Abs. 4 UStG',
  subtitle_en: 'Mandatory fields per § 14(4) UStG',
  legal_references: [
    {
      law: 'UStG',
      section: '§ 14 Abs. 4',
      description_de: 'Pflichtangaben in Rechnungen',
      description_en: 'Mandatory invoice fields',
    },
    {
      law: 'UStG',
      section: '§ 15',
      description_de: 'Vorsteuerabzug',
      description_en: 'Input tax deduction',
    },
    {
      law: 'UStDV',
      section: '§ 33',
      description_de: 'Kleinbetragsrechnungen',
      description_en: 'Small amount invoices',
    },
  ],
  supported_document_types: ['INVOICE'],
  small_amount_threshold: 250,
  small_amount_currency: 'EUR',
  vat_rates: [19, 7],
  features: [
    {
      feature_id: 'supplier_name_address',
      name_de: 'Name und Anschrift des Lieferanten',
      name_en: 'Supplier name and address',
      legal_basis: '§ 14 Abs. 4 Nr. 1 UStG',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Vollständiger Name und Anschrift des leistenden Unternehmers (Straße, PLZ, Ort)',
      explanation_en: 'Full name and address of the supplier (street, postal code, city)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'customer_name_address',
      name_de: 'Name und Anschrift des Empfängers',
      name_en: 'Customer name and address',
      legal_basis: '§ 14 Abs. 4 Nr. 1 UStG',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Vollständiger Name und Anschrift des Leistungsempfängers',
      explanation_en: 'Full name and address of the customer/recipient',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supplier_tax_or_vat_id',
      name_de: 'Steuernummer oder USt-ID',
      name_en: 'Tax number or VAT ID',
      legal_basis: '§ 14 Abs. 4 Nr. 2 UStG',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Steuernummer (z.B. 123/456/78901) oder Umsatzsteuer-Identifikationsnummer (DE123456789)',
      explanation_en: 'German tax number or VAT identification number (DE followed by 9 digits)',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'invoice_date',
      name_de: 'Rechnungsdatum',
      name_en: 'Invoice date',
      legal_basis: '§ 14 Abs. 4 Nr. 3 UStG',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Ausstellungsdatum der Rechnung',
      explanation_en: 'Date when the invoice was issued',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'invoice_number',
      name_de: 'Rechnungsnummer',
      name_en: 'Invoice number',
      legal_basis: '§ 14 Abs. 4 Nr. 4 UStG',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Fortlaufende, einmalige Rechnungsnummer zur eindeutigen Identifikation',
      explanation_en: 'Sequential, unique invoice number for identification',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supply_description',
      name_de: 'Leistungsbeschreibung',
      name_en: 'Description of supply',
      legal_basis: '§ 14 Abs. 4 Nr. 5 UStG',
      required_level: 'REQUIRED',
      category: 'TEXT',
      explanation_de: 'Art (handelsübliche Bezeichnung) und Umfang der Lieferung oder sonstigen Leistung',
      explanation_en: 'Type and scope of the goods delivered or services provided',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'supply_date_or_period',
      name_de: 'Liefer-/Leistungszeitraum',
      name_en: 'Date/period of supply',
      legal_basis: '§ 14 Abs. 4 Nr. 6 UStG',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Zeitpunkt der Lieferung oder sonstigen Leistung, oder Hinweis auf Rechnungsdatum',
      explanation_en: 'Date when supply was made, or period of service delivery',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'net_amount',
      name_de: 'Nettobetrag',
      name_en: 'Net amount',
      legal_basis: '§ 14 Abs. 4 Nr. 7 UStG',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Entgelt (Summe ohne Umsatzsteuer), aufgeschlüsselt nach Steuersätzen',
      explanation_en: 'Net price excluding VAT, broken down by tax rates',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'vat_rate',
      name_de: 'Steuersatz',
      name_en: 'VAT rate',
      legal_basis: '§ 14 Abs. 4 Nr. 8 UStG',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Anzuwendender Steuersatz (19% Regelsteuersatz oder 7% ermäßigt)',
      explanation_en: 'Applicable VAT rate (19% standard or 7% reduced)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'vat_amount',
      name_de: 'Steuerbetrag',
      name_en: 'VAT amount',
      legal_basis: '§ 14 Abs. 4 Nr. 8 UStG',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Auf das Entgelt entfallender Steuerbetrag (Netto × Steuersatz)',
      explanation_en: 'VAT amount calculated on net price',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'gross_amount',
      name_de: 'Bruttobetrag',
      name_en: 'Gross amount',
      legal_basis: '§ 14 Abs. 4 UStG',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Gesamtbetrag inkl. Umsatzsteuer (Netto + MwSt)',
      explanation_en: 'Total amount including VAT',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'tax_exemption_reason',
      name_de: 'Steuerbefreiungsgrund',
      name_en: 'Tax exemption reason',
      legal_basis: '§ 14 Abs. 4 Nr. 8 UStG',
      required_level: 'CONDITIONAL',
      category: 'TAX',
      explanation_de: 'Hinweis auf Steuerbefreiung (z.B. "Innergemeinschaftliche Lieferung gemäß § 4 Nr. 1b UStG")',
      explanation_en: 'Reference to tax exemption if applicable',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
  ],
};

export default DE_USTG;
