/**
 * EU_VAT Ruleset - EU MwSt-Systemrichtlinie
 *
 * Pflichtangaben nach Art. 226 RL 2006/112/EG
 */

import type { Ruleset } from './types';

export const EU_VAT: Ruleset = {
  ruleset_id: 'EU_VAT',
  version: '1.0.0',
  jurisdiction: 'EU',
  flag: '🇪🇺',
  title_de: 'EU – MwSt-Systemrichtlinie',
  title_en: 'EU – VAT Directive',
  subtitle_de: 'Pflichtangaben nach Art. 226 RL 2006/112/EG',
  subtitle_en: 'Mandatory fields per Article 226 Directive 2006/112/EC',
  legal_references: [
    {
      law: 'RL 2006/112/EG',
      section: 'Art. 226',
      description_de: 'Pflichtangaben in Rechnungen',
      description_en: 'Mandatory invoice particulars',
    },
    {
      law: 'RL 2006/112/EG',
      section: 'Art. 238',
      description_de: 'Vereinfachte Rechnungen',
      description_en: 'Simplified invoices',
    },
  ],
  small_amount_threshold: 400,
  small_amount_currency: 'EUR',
  features: [
    {
      feature_id: 'invoice_date',
      name_de: 'Ausstellungsdatum',
      name_en: 'Date of issue',
      legal_basis: 'Art. 226 Nr. 1',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Datum der Rechnungsausstellung',
      explanation_en: 'Date when the invoice was issued',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'invoice_number',
      name_de: 'Fortlaufende Nummer',
      name_en: 'Sequential number',
      legal_basis: 'Art. 226 Nr. 2',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Fortlaufende Nummer mit einer oder mehreren Zahlenreihen zur eindeutigen Identifikation',
      explanation_en: 'Sequential number based on one or more series uniquely identifying the invoice',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supplier_vat_id',
      name_de: 'USt-ID des Lieferanten',
      name_en: 'Supplier VAT ID',
      legal_basis: 'Art. 226 Nr. 3',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Umsatzsteuer-Identifikationsnummer des Lieferanten (EU-Format: Ländercode + Nummer)',
      explanation_en: 'VAT identification number of the supplier (EU format: country code + number)',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'customer_vat_id',
      name_de: 'USt-ID des Kunden (B2B)',
      name_en: 'Customer VAT ID (B2B)',
      legal_basis: 'Art. 226 Nr. 4',
      required_level: 'CONDITIONAL',
      category: 'IDENTITY',
      explanation_de: 'USt-ID des Erwerbers bei innergemeinschaftlichen Lieferungen oder Reverse Charge',
      explanation_en: 'Customer VAT ID required for intra-community supplies or reverse charge',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supplier_name_address',
      name_de: 'Name und Anschrift Lieferant',
      name_en: 'Supplier name and address',
      legal_basis: 'Art. 226 Nr. 5',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Vollständiger Name und Anschrift des Steuerpflichtigen (Lieferant)',
      explanation_en: 'Full name and address of the taxable person (supplier)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'customer_name_address',
      name_de: 'Name und Anschrift Kunde',
      name_en: 'Customer name and address',
      legal_basis: 'Art. 226 Nr. 6',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Vollständiger Name und Anschrift des Erwerbers oder Dienstleistungsempfängers',
      explanation_en: 'Full name and address of the customer',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supply_description',
      name_de: 'Leistungsbeschreibung',
      name_en: 'Description of goods/services',
      legal_basis: 'Art. 226 Nr. 6',
      required_level: 'REQUIRED',
      category: 'TEXT',
      explanation_de: 'Menge und Art der gelieferten Gegenstände bzw. Umfang und Art der Dienstleistungen',
      explanation_en: 'Quantity and nature of goods supplied or extent and nature of services',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'supply_date',
      name_de: 'Lieferdatum',
      name_en: 'Date of supply',
      legal_basis: 'Art. 226 Nr. 7',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Datum der Lieferung oder Dienstleistung, falls abweichend vom Rechnungsdatum',
      explanation_en: 'Date when supply was made, if different from invoice date',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'taxable_amount',
      name_de: 'Bemessungsgrundlage',
      name_en: 'Taxable amount',
      legal_basis: 'Art. 226 Nr. 8',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Steuerbemessungsgrundlage je Steuersatz oder Befreiung',
      explanation_en: 'Tax base for each rate or exemption',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'unit_price',
      name_de: 'Einzelpreis (netto)',
      name_en: 'Unit price (excl. VAT)',
      legal_basis: 'Art. 226 Nr. 9',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Preis je Einheit ohne Steuer sowie etwaige Rabatte',
      explanation_en: 'Unit price excluding VAT and any discounts',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'vat_rate',
      name_de: 'Steuersatz',
      name_en: 'VAT rate',
      legal_basis: 'Art. 226 Nr. 10',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Anzuwendender Mehrwertsteuersatz',
      explanation_en: 'Applicable VAT rate',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'vat_amount',
      name_de: 'Steuerbetrag',
      name_en: 'VAT amount',
      legal_basis: 'Art. 226 Nr. 10',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Zu zahlender MwSt-Betrag (außer bei Steuerbefreiung)',
      explanation_en: 'VAT amount payable (except where exempt)',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'exemption_reason',
      name_de: 'Steuerbefreiungsgrund',
      name_en: 'Exemption reference',
      legal_basis: 'Art. 226 Nr. 11',
      required_level: 'CONDITIONAL',
      category: 'TAX',
      explanation_de: 'Hinweis auf Steuerbefreiung mit Verweis auf die einschlägige Bestimmung',
      explanation_en: 'Reference to exemption provision of the Directive',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'reverse_charge_notice',
      name_de: 'Reverse-Charge-Hinweis',
      name_en: 'Reverse charge notice',
      legal_basis: 'Art. 226 Nr. 11a',
      required_level: 'CONDITIONAL',
      category: 'TAX',
      explanation_de: 'Hinweis "Steuerschuldnerschaft des Leistungsempfängers" bei Reverse Charge',
      explanation_en: 'Notice "Reverse charge" when customer is liable for VAT',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'margin_scheme_notice',
      name_de: 'Differenzbesteuerung',
      name_en: 'Margin scheme notice',
      legal_basis: 'Art. 226 Nr. 14',
      required_level: 'CONDITIONAL',
      category: 'TAX',
      explanation_de: 'Hinweis auf Differenzbesteuerung (z.B. "Gebrauchtgegenstände / Sonderregelung")',
      explanation_en: 'Reference to margin scheme if applicable',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
  ],
};

export default EU_VAT;
