/**
 * UK_VAT Ruleset - HMRC VAT Notice 700
 *
 * Pflichtangaben nach UK VAT-Recht
 */

import type { Ruleset } from './types';

export const UK_VAT: Ruleset = {
  ruleset_id: 'UK_VAT',
  version: '1.0.0',
  jurisdiction: 'UK',
  flag: '🇬🇧',
  title_de: 'UK – HMRC VAT',
  title_en: 'UK – HMRC VAT',
  subtitle_de: 'Pflichtangaben nach VAT Notice 700',
  subtitle_en: 'Mandatory fields per VAT Notice 700',
  legal_references: [
    {
      law: 'VAT Act 1994',
      section: 'Schedule 11',
      description_de: 'Rechnungsanforderungen',
      description_en: 'VAT invoice requirements',
    },
    {
      law: 'HMRC VAT Notice 700',
      section: 'Section 16',
      description_de: 'MwSt-Rechnungen',
      description_en: 'VAT invoices',
    },
  ],
  supported_document_types: ['INVOICE'],
  small_amount_threshold: 250,
  small_amount_currency: 'GBP',
  vat_rates: [20, 5, 0],
  features: [
    {
      feature_id: 'supplier_name_address',
      name_de: 'Name und Anschrift Lieferant',
      name_en: 'Supplier name and address',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Name, Anschrift und VAT-Nummer des Lieferanten',
      explanation_en: 'Name, address and VAT registration number of the supplier',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'supplier_vat_number',
      name_de: 'VAT-Registrierungsnummer',
      name_en: 'VAT registration number',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'UK VAT-Nummer des Lieferanten (GB + 9 oder 12 Ziffern)',
      explanation_en: 'UK VAT registration number (GB followed by 9 or 12 digits)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'invoice_number',
      name_de: 'Eindeutige Rechnungsnummer',
      name_en: 'Unique identifying number',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Eindeutige Identifikationsnummer der Rechnung',
      explanation_en: 'Unique identifying number for the invoice',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'invoice_date',
      name_de: 'Rechnungsdatum',
      name_en: 'Date of issue',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Datum der Rechnungsausstellung',
      explanation_en: 'Date the invoice was issued',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'tax_point',
      name_de: 'Steuerzeitpunkt (Tax Point)',
      name_en: 'Time of supply (Tax Point)',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'DATE',
      explanation_de: 'Zeitpunkt, zu dem die MwSt fällig wird (kann vom Rechnungsdatum abweichen)',
      explanation_en: 'Date when VAT becomes due - may differ from invoice date',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'customer_name_address',
      name_de: 'Name und Anschrift Kunde',
      name_en: 'Customer name and address',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'IDENTITY',
      explanation_de: 'Name und Anschrift des Kunden',
      explanation_en: 'Name and address of the customer',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'supply_description',
      name_de: 'Leistungsbeschreibung',
      name_en: 'Description of goods/services',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'TEXT',
      explanation_de: 'Beschreibung der gelieferten Waren oder erbrachten Dienstleistungen',
      explanation_en: 'Description of the goods or services supplied',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'quantity',
      name_de: 'Menge',
      name_en: 'Quantity of goods',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Menge der gelieferten Waren',
      explanation_en: 'Quantity of goods supplied',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'unit_price',
      name_de: 'Einzelpreis (netto)',
      name_en: 'Unit price (excl. VAT)',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Preis pro Einheit ohne MwSt',
      explanation_en: 'Unit price excluding VAT',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'vat_rate',
      name_de: 'MwSt-Satz',
      name_en: 'Rate of VAT',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Anzuwendender MwSt-Satz (20% Standard, 5% ermäßigt, 0% Nullsatz)',
      explanation_en: 'Applicable VAT rate (20% standard, 5% reduced, 0% zero-rated)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
    {
      feature_id: 'total_excl_vat',
      name_de: 'Summe ohne MwSt',
      name_en: 'Total excluding VAT',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Gesamtbetrag ohne Mehrwertsteuer',
      explanation_en: 'Total amount excluding VAT',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'total_vat',
      name_de: 'MwSt-Betrag',
      name_en: 'Total VAT charged',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'TAX',
      explanation_de: 'Gesamtbetrag der berechneten Mehrwertsteuer',
      explanation_en: 'Total amount of VAT charged',
      applies_to: { standard_invoice: true, small_amount_invoice: false },
    },
    {
      feature_id: 'total_incl_vat',
      name_de: 'Zahlbetrag',
      name_en: 'Total amount payable',
      legal_basis: 'VAT Notice 700',
      required_level: 'REQUIRED',
      category: 'AMOUNT',
      explanation_de: 'Gesamtbetrag inkl. Mehrwertsteuer (zu zahlender Betrag)',
      explanation_en: 'Total amount including VAT (amount payable)',
      applies_to: { standard_invoice: true, small_amount_invoice: true },
    },
  ],
};

export default UK_VAT;
